store-before/config/routes.rb
Store::Application.routes.draw do
  resources :products
  root to: 'products#index'
end

store-before/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

store-before/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :category_id
  belongs_to :category
  has_many :reviews
end

store-before/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

store-before/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  has_many :reviews
end

store-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

store-before/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order("name")
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end
end

store-before/app/helpers/application_helper.rb
module ApplicationHelper
end

store-before/app/helpers/products_helper.rb
module ProductsHelper
end

store-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

store-before/app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

store-before/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

store-before/app/views/products/index.html.erb
<h1>Products</h1>

<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Category</th>
    <th>Price</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to product.name, product %></td>
    <td><%= product.category.name %></td>
    <td class="price"><%= number_to_currency(product.price) %></td>
    <td><%= link_to "edit", edit_product_path(product) %></td>
  </tr>
<% end %>
</table>

store-before/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

store-before/app/views/products/show.html.erb
<h1>Product Details</h1>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back to Products', products_path %>
</p>